const Menu = [
  {
    id: 1,
    image: process.env.PUBLIC_URL + "/images/corn.jpg",
    name: "Corn",
    category: "Breakfast",
    price: "10₹",
    description: "Steamed sweet corn tossed with butter and mild spices.",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + "/images/paubhaji.jpg",
    name: "Pav Bhaji",
    category: "Breakfast",
    price: "50₹",
    description: "Spicy mashed vegetables served with butter-toasted pav.",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + "/images/puri.jpg",
    name: "Puri Bhaji",
    category: "Breakfast",
    price: "50₹",
    description: "Fluffy puris served with flavorful potato curry.",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + "/images/chola.jpg",
    name: "Chola",
    category: "Lunch",
    price: "60₹",
    description: "Punjabi-style chickpeas cooked in rich masala gravy.",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + "/images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "Lunch",
    price: "80₹",
    description: "Red kidney beans in a tangy tomato gravy with rice.",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + "/images/maggi.jpg",
    name: "Maggi",
    category: "Evening",
    price: "20₹",
    description: "Instant noodles cooked with veggies and Indian spices.",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + "/images/pizza.jpg",
    name: "Pizza",
    category: "Evening",
    price: "100₹",
    description: "Crispy base loaded with cheese and fresh toppings.",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + "/images/samosa.jpg",
    name: "Samosa",
    category: "Evening",
    price: "20₹",
    description: "Deep-fried pastry filled with spicy mashed potatoes.",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + "/images/momo.jpg",
    name: "Momos",
    category: "Evening",
    price: "60₹",
    description: "Soft dumplings stuffed with spiced veggies or meat.",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + "/images/vegthali.jpg",
    name: "Veg Thali",
    category: "Dinner",
    price: "200₹",
    description: "Complete Indian vegetarian meal with multiple dishes.",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + "/images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "Dinner",
    price: "250₹",
    description: "Hearty thali with chicken curry, rice, roti, and sides.",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + "/images/sweet.jpg",
    name: "Sweets",
    category: "Dinner",
    price: "100₹",
    description: "Assorted Indian sweets to end your meal on a high note.",
  },
];

export default Menu;


