const Menu = [
  {
    id: 1,
    image: process.env.PUBLIC_URL + "/images/corn.jpg",
    name: "corn",
    category: "Breakfast",
    price: "10₹",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + "/images/paubhaji.jpg",
    name: "Pav Bhaji",
    category: "Breakfast",
    price: "50₹",
    description: "Lorem ipsum...",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + "/images/puri.jpg",
    name: "Puri Bhaji",
    category: "Breakfast",
    price: "50₹",
    description: "Lorem ipsum...",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + "/images/chola.jpg",
    name: "chola",
    category: "Lunch",
    price: "60₹",
    description: "Lorem ipsum...",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + "/images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "Lunch",
    price: "80₹",
    description: "Lorem ipsum...",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + "/images/maggi.jpg",
    name: "maggi",
    category: "Evening",
    price: "20₹",
    description: "Lorem ipsum...",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + "/images/pizza.jpg",
    name: "pizza",
    category: "Evening",
    price: "100₹",
    description: "Lorem ipsum...",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + "/images/samosa.jpg",
    name: "samosa",
    category: "Evening",
    price: "20₹",
    description: "Lorem ipsum...",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + "/images/momo.jpg",
    name: "Momos",
    category: "Evening",
    price: "60₹",
    description: "Lorem ipsum...",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + "/images/vegthali.jpg",
    name: "Veg Thali",
    category: "Dinner",
    price: "200₹",
    description: "Lorem ipsum...",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + "/images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "Dinner",
    price: "250₹",
    description: "Lorem ipsum...",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + "/images/sweet.jpg",
    name: "Sweets",
    category: "Dinner",
    price: "100₹",
    description: "Lorem ipsum...",
  },
];

export default Menu;

